
name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *" # Update otomatis setiap 12 jam
  workflow_dispatch: # Memungkinkan untuk menjalankan secara manual
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: <username-anda> # Ganti dengan username GitHub Anda
          outputs: |
            snake.svg?palette=github-dark&color_snake=blue

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          keep_files: true
